FROM mcr.microsoft.com/dotnet/core/sdk:3.1
WORKDIR /
RUN mkdir /src
RUN mkdir /src/ProjectEulerSolution
WORKDIR /
COPY ./src/ProjectEulerSolution src/ProjectEulerSolution

# build
WORKDIR /src/ProjectEulerSolution
RUN dotnet build -c Release

# publish
WORKDIR /
RUN mkdir /release
WORKDIR /src/ProjectEulerSolution/ProjectEuler.Web
RUN dotnet publish -c Release -o /release

# deploy to heroku
WORKDIR /release
CMD ASPNETCORE_URLS=http://*:$PORT dotnet ProjectEuler.Web.dll
