name: "Publish"

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - Dockerfile.web
      - .github/workflows/Publish.yml

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Deploy to Heroku
        run: |
          heroku container:login
          heroku container:push web --recursive -a ${HEROKU_APP_NAME}
          heroku container:release web -a ${HEROKU_APP_NAME}
        env:
          HEROKU_APP_NAME: ushibutatory-pj-euler-dotnet
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
